{{- range .Values.backend}}
apiVersion: apps/v1
kind: Deployment
metadata:
 name: {{ .name }}
 namespace: {{ $.Values.namespace.name }}
 labels:
  app: {{ .name}}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.backendrepositoryName}}:{{ .tag}}"
          ports:
            - containerPort: {{ .port }}
          envFrom:
            - configMapRef:
                name: streaming-app-config
            - secretRef:
                name: streaming-app-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
 name: {{ .name }}-service
 namespace: {{ $.Values.namespace.name}}
spec:
  selector:
    app: {{ .name}}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
  type: ClusterIP                      
---
{{- end }} 
