apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-app-config
  namespace: streaming-app
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  CLIENT_URLS: "http://ac758a9991a534495b9be202b02f9084-1588338655.us-east-1.elb.amazonaws.com"
  STREAMING_PUBLIC_URL: "http://ac758a9991a534495b9be202b02f9084-1588338655.us-east-1.elb.amazonaws.com/api/streaming"
  MONGO_DB: "streamingapp"
  AWS_REGION: "us-east-1"
  AWS_S3_BUCKET: "dev-streaming-app"
  REACT_APP_AUTH_API_URL: "http://ac758a9991a534495b9be202b02f9084-1588338655.us-east-1.elb.amazonaws.com/api"
  REACT_APP_STREAMING_API_URL: "http://ac758a9991a534495b9be202b02f9084-1588338655.us-east-1.elb.amazonaws.com/api/streaming"
  REACT_APP_STREAMING_PUBLIC_URL: "http://ac758a9991a534495b9be202b02f9084-1588338655.us-east-1.elb.amazonaws.com/api/streaming"
