apiVersion: apps/v1
kind: Deployment
metadata:
 name: streaming-frontend
 namespace: {{ .Values.namespace.name}}
 labels:
  app: frontend-service
spec:
  replicas: {{ .Values.frontend.replicaCount}}
  selector:
    matchLabels:
      app: streaming-frontend
  template:
    metadata:
      labels:
        app: streaming-frontend
    spec:
      containers:
        - name: streaming-frontend
          image: "{{ .Values.frontendrepositoryName}}:{{ .Values.frontend.image.tag}}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: streaming-app-config
            - secretRef:
                name: streaming-app-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
 name: streaming-app-frontend-service
 namespace: {{ .Values.namespace.name}}
spec:
  selector:
    app: streaming-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
