apiVersion: v1
kind: Secret
metadata:
  name: streaming-app-secrets
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  AWS_ACCESS_KEY: {{ .Values.secrets.awsAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretKey }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  MONGO_URI: {{ .Values.secrets.mongoUri }}